import {
  Document,
  HeadingLevel,
  PageBreak,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

import type { PdfExtractedParagraph, PdfExtractedPage } from "@/types/pdf";

const DOCX_MIME_TYPE =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

function createHeadingParagraph(text: string) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 140 },
  });
}

function createBodyParagraph(text: string) {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    spacing: { before: 80, after: 180, line: 320 },
  });
}

function createListParagraph(text: string) {
  const cleanedText = text.replace(/^\s*(?:[-*•]|\d+[.)]|[a-zA-Z][.)])\s+/, "");

  return new Paragraph({
    children: [new TextRun({ text: cleanedText || text, size: 22 })],
    bullet: { level: 0 },
    spacing: { after: 120, line: 300 },
  });
}

function createTableLikeParagraph(paragraph: PdfExtractedParagraph) {
  return paragraph.lines.map(
    (line) =>
      new Paragraph({
        children: [
          new TextRun({
            text: line.text,
            font: "Courier New",
            size: 20,
          }),
        ],
        spacing: { after: 80, line: 280 },
      })
  );
}

function renderParagraph(paragraph: PdfExtractedParagraph) {
  if (paragraph.type === "heading") {
    return [createHeadingParagraph(paragraph.text)];
  }

  if (paragraph.type === "list") {
    return paragraph.lines.map((line) => createListParagraph(line.text));
  }

  if (paragraph.type === "table-like") {
    return createTableLikeParagraph(paragraph);
  }

  return [createBodyParagraph(paragraph.text)];
}

export async function createWordDocumentFromPages(
  pages: PdfExtractedPage[]
): Promise<Blob> {
  try {
    const children: Paragraph[] = [
      new Paragraph({
        text: "Converted Document",
        heading: HeadingLevel.TITLE,
        spacing: { after: 180 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: "Generated by PDFCraft",
            italics: true,
            color: "64748B",
            size: 20,
          }),
        ],
        spacing: { after: 360 },
      }),
    ];

    pages.forEach((page, index) => {
      if (index > 0) {
        children.push(new Paragraph({ children: [new PageBreak()] }));
      }

      children.push(
        new Paragraph({
          text: `Page ${page.pageNumber}`,
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 120, after: 240 },
        })
      );

      if (page.paragraphs.length === 0) {
        children.push(createBodyParagraph("No readable text on this page."));
        return;
      }

      for (const paragraph of page.paragraphs) {
        children.push(...renderParagraph(paragraph));
      }
    });

    const document = new Document({
      creator: "PDFCraft",
      title: "Converted Document",
      description: "PDF text converted into an editable Word document.",
      sections: [
        {
          properties: {},
          children,
        },
      ],
      styles: {
        default: {
          document: {
            run: {
              font: "Aptos",
              size: 22,
            },
            paragraph: {
              spacing: { line: 320 },
            },
          },
        },
      },
    });

    const packed = await Packer.toBlob(document);
    const copy = await packed.arrayBuffer();

    return new Blob([copy], { type: DOCX_MIME_TYPE });
  } catch (error) {
    throw new Error(
      error instanceof Error
        ? `Unable to create Word document: ${error.message}`
        : "Unable to create Word document."
    );
  }
}
